name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - python-dotenv
  - pip
  - pip:
    - langchain
    - langchain-openai
    - langchain-qdrant
    - qdrant-client
    - langchain_community
    - sentence-transformers
