name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - python-dotenv
  - pip
  - pip:
    - langchain
    - langchain_community
    - sentence-transformers
    - langchain-chroma
    - chromadb
